################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../pervasive/FPL_drivers/Board_HW_Driver.c \
../pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.c \
../pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.c \
../pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.c \
../pervasive/FPL_drivers/iTC_215_Aurora_Mb.c \
../pervasive/FPL_drivers/iTC_287_Aurora_Mb.c \
../pervasive/FPL_drivers/iTC_287_Spectra.c \
../pervasive/FPL_drivers/iTC_420_Aurora_Mb.c \
../pervasive/FPL_drivers/iTC_420_Spectra.c \
../pervasive/FPL_drivers/iTC_Engine.c 

OBJS += \
./pervasive/FPL_drivers/Board_HW_Driver.o \
./pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.o \
./pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.o \
./pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.o \
./pervasive/FPL_drivers/iTC_215_Aurora_Mb.o \
./pervasive/FPL_drivers/iTC_287_Aurora_Mb.o \
./pervasive/FPL_drivers/iTC_287_Spectra.o \
./pervasive/FPL_drivers/iTC_420_Aurora_Mb.o \
./pervasive/FPL_drivers/iTC_420_Spectra.o \
./pervasive/FPL_drivers/iTC_Engine.o 

C_DEPS += \
./pervasive/FPL_drivers/Board_HW_Driver.d \
./pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.d \
./pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.d \
./pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.d \
./pervasive/FPL_drivers/iTC_215_Aurora_Mb.d \
./pervasive/FPL_drivers/iTC_287_Aurora_Mb.d \
./pervasive/FPL_drivers/iTC_287_Spectra.d \
./pervasive/FPL_drivers/iTC_420_Aurora_Mb.d \
./pervasive/FPL_drivers/iTC_420_Spectra.d \
./pervasive/FPL_drivers/iTC_Engine.d 


# Each subdirectory must supply rules for building sources it contributes
pervasive/FPL_drivers/Board_HW_Driver.o: ../pervasive/FPL_drivers/Board_HW_Driver.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/Board_HW_Driver.d" -MT"pervasive/FPL_drivers/Board_HW_Driver.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.o: ../pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.d" -MT"pervasive/FPL_drivers/eTC_G1_Size_Aurora_Mb.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.o: ../pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.d" -MT"pervasive/FPL_drivers/eTC_G2_Size_Aurora_Ma.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.o: ../pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.d" -MT"pervasive/FPL_drivers/eTC_G2_Size_Aurora_Mb.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/iTC_215_Aurora_Mb.o: ../pervasive/FPL_drivers/iTC_215_Aurora_Mb.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/iTC_215_Aurora_Mb.d" -MT"pervasive/FPL_drivers/iTC_215_Aurora_Mb.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/iTC_287_Aurora_Mb.o: ../pervasive/FPL_drivers/iTC_287_Aurora_Mb.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/iTC_287_Aurora_Mb.d" -MT"pervasive/FPL_drivers/iTC_287_Aurora_Mb.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/iTC_287_Spectra.o: ../pervasive/FPL_drivers/iTC_287_Spectra.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/iTC_287_Spectra.d" -MT"pervasive/FPL_drivers/iTC_287_Spectra.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/iTC_420_Aurora_Mb.o: ../pervasive/FPL_drivers/iTC_420_Aurora_Mb.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/iTC_420_Aurora_Mb.d" -MT"pervasive/FPL_drivers/iTC_420_Aurora_Mb.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/iTC_420_Spectra.o: ../pervasive/FPL_drivers/iTC_420_Spectra.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/iTC_420_Spectra.d" -MT"pervasive/FPL_drivers/iTC_420_Spectra.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pervasive/FPL_drivers/iTC_Engine.o: ../pervasive/FPL_drivers/iTC_Engine.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM48=1' -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\halconfig" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emlib\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\drivers" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\common\bsp" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\CMSIS\Include" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\chip\efr32" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\hardware\kit\EFR32BG1_BRD4300C\config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\tempdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\app\bluetooth_2.7\common\stack_bridge" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\radio\rail_lib\common" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\src" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\common\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\sleep\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\halconfig\inc\hal-config" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\uartdrv\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\emdrv\gpiointerrupt\inc" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader\api" -I"C:\Users\Salva\SimplicityStudio\v4_workspace\Transfer-v0\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pervasive/FPL_drivers/iTC_Engine.d" -MT"pervasive/FPL_drivers/iTC_Engine.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


